pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout Code from GitHub'
                // Checkout the code from your Git repository
                git branch: 'master', url: 'https://github.com/Rekapost/ParaBankCucumberBDD.git'
            }
        }

        stage('Build and Test') {
            steps {
                echo 'Running Maven tests'
                // Run your Maven tests using the testng.xml configuration file
                bat 'mvn clean test'  // Adjust if you have a specific testng.xml or configuration
            }
        }

        stage('Static Code Analysis') {
           environment {
                SONAR_URL = "http://localhost:9000"
            }
                steps {
                    withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                        echo "SonarQube URL: ${SONAR_URL}"
                        bat "mvn clean verify sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.login=$SONAR_AUTH_TOKEN"
                    }
                }
            }

                stage('Check Docker Version') {
                    steps {
                        script {
                            bat 'docker --version'
                        }
                    }
                }
        
         stage('Post-test Cleanup') {
            steps {
                echo 'Cleaning up after tests'
                // Optional: Run cleanup tasks
                bat 'docker container prune -f'  // Example cleanup command
            }
        }

    }

    post {
        success {
            echo 'Tests passed successfully!'
        }
        failure {
            echo 'Tests failed, please check the logs.'
        }
    }
}

/*
pipeline {
    agent any
    stages {
        stage('Build and Test') {
            steps {
                bat 'C:\\Users\\nreka\\git\\repository\\Testng_Framework\\run.bat'
            }
        }
    }
}
*/