name: Parabank-bdd-cucumber CI/CD Pipeline

on:
  workflow_dispatch:      # Only runs manually
  #push:
   #branches:
     # - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code            # Checkout source code 
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
    
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          sudo apt install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Verify ChromeDriver installation
        run: chromedriver --version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

  #    - name: Run TestNG tests
    #    run: mvn test
  
  # 🔹 SonarQube Analysis Step
      #- name: Run SonarQube Analysis
      #  run: mvn sonar:sonar -Dsonar.projectKey=Parabank-bdd-cucumber -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}



